### ISSUE TITLE
能新增 tab “专栏” 吗？

### ISSUE THREAD

**Issue by TUARAN** [TeaTools/auto-sync-blog#4]
不礼貌的提个需求：能把专栏的内容也扒出来放到一个 Tab 下吗？hhhh

**Comment by tea-blog** [comment]
是打算要这样做的：是要把用户和专栏区分来，主要围绕用户所在的平台去做，专栏作为辅助丰富内容，不仅区分自己的专栏还额外能添加别人的专栏。只想了大概方向，但是还没去细想完整的，并且欢迎各位大佬有更好的思路也可以提供一下一起讨论学习。
: )

**Comment by tea-blog** [comment]
你好，已更新v0.0.2，可同步更新一下看看。原参数不需要改变。: )
